In [8]:
import tensorflow as tf
import numpy as np


In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [6]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128 , activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.14623342, -0.3060006 ,  0.09655526,  0.12974575, -0.22114   ,
         0.04408228,  0.07189522,  0.50548476, -0.3344128 ,  0.10234803]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.10985518, 0.06989044, 0.10453111, 0.10805876, 0.07608031,
        0.09918748, 0.10198489, 0.15734081, 0.06793264, 0.10513838]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1],predictions).numpy()

2.3107436

In [15]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [17]:
model.fit(x_train , y_train , epochs = 5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 101us/sample - loss: 0.2955 - accuracy: 0.9141
Epoch 2/5
60000/60000 [==============================] - 5s 82us/sample - loss: 0.1419 - accuracy: 0.9580
Epoch 3/5
60000/60000 [==============================] - 5s 84us/sample - loss: 0.1059 - accuracy: 0.9678
Epoch 4/5
60000/60000 [==============================] - 5s 83us/sample - loss: 0.0878 - accuracy: 0.9728
Epoch 5/5
60000/60000 [==============================] - 5s 84us/sample - loss: 0.0745 - accuracy: 0.9762


In [19]:
model.evaluate(x_test , y_test , verbose=2)

10000/1 - 0s - loss: 0.0373 - accuracy: 0.9777


[0.07291473617162555, 0.9777]

In [20]:
probability_model = tf.keras.Sequential([
    model,tf.keras.layers.Softmax()
])

In [21]:
probability_model(x_test[:5])

<tf.Tensor: id=30028, shape=(5, 10), dtype=float32, numpy=
array([[1.3459406e-08, 5.8065006e-09, 1.0373656e-05, 3.9052513e-05,
        1.5365766e-11, 1.5736900e-08, 5.8562558e-15, 9.9994755e-01,
        5.3381125e-08, 2.9655278e-06],
       [3.0807946e-08, 3.6139946e-04, 9.9958140e-01, 4.6067664e-05,
        1.4404698e-13, 4.1944304e-06, 6.1348231e-07, 2.1480558e-12,
        6.3157345e-06, 1.7437883e-11],
       [7.1949034e-07, 9.9877065e-01, 8.3062449e-05, 2.3041845e-05,
        4.8754799e-05, 1.1203972e-05, 3.3459026e-05, 7.3684804e-04,
        2.9128024e-04, 9.1947277e-07],
       [9.9950051e-01, 8.8266553e-08, 6.8970818e-05, 6.3398197e-06,
        3.6494050e-06, 3.9486829e-05, 3.7847029e-05, 1.6252977e-04,
        3.5530468e-07, 1.8013807e-04],
       [2.0728189e-04, 4.3417576e-09, 4.5779230e-05, 1.4934761e-05,
        9.5178831e-01, 5.4949928e-06, 1.9524043e-06, 1.0379639e-03,
        1.2746972e-05, 4.6885714e-02]], dtype=float32)>

In [22]:
print(tf.version)

<module 'tensorflow_core._api.v2.version' from 'C:\\Users\\Salma\\miniconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow_core\\_api\\v2\\version\\__init__.py'>
